apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skattetrekk-legacy-redirect-ingress-prod
  namespace: okonomi
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.nav.no/utbetaling/frivillig-skattetrekk"
  labels:
    app: skattetrekk-legacy-redirect-ingress-prod
    team: okonomi
spec:
  ingressClassName: nais-ingress-external
  rules:
    - http:
        paths:
          - path: /utbetaling/skattetrekk
            pathType: Prefix
            backend:
              service:
                name: sokos-frivillig-skattetrekk-backend
                port:
                  number: 80