apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-frivillig-skattetrekk-frontend-q2
  namespace: okonomi
  labels:
    team: okonomi
  annotations:
    nais.io/run-as-user: "101" # nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
spec:
  image: "{{{ image }}}"
  port: 8080
  ingresses:
    - https://sokos-frivillig-skattetrekk-frontend-q2.intern.dev.nav.no/utbetaling/skattetrekk
    - https://sokos-frivillig-skattetrekk-frontend-q2.ansatt.dev.nav.no/utbetaling/skattetrekk
  replicas:
    min: 1
    max: 2
  liveness:
    path: /utbetaling/frivillig-skattetrekk/internal/isAlive
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  readiness:
    path: /utbetaling/frivillig-skattetrekk/internal/isReady
    initialDelay: 20
    periodSeconds: 20
    failureThreshold: 5
    timeout: 1
  frontend:
    generatedConfig:
      mountPath: /usr/share/nginx/html/assets/nais.js
  idporten:
    enabled: true
    sidecar:
      level: idporten-loa-substantial
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /internal/ping
  tokenx:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
      destinations:
        - id: "grafana-lgtm"
    logging:
      destinations:
        - id: elastic
        - id: loki
  accessPolicy:
    inbound:
      rules:
        - application: wonderwalled-idporten
          namespace: aura
    outbound:
      external:
        - host: sokos-frivillig-skattetrekk-backend-q2.dev-fss-pub.nais.io

  env:
    - name: "VITE_DECORATOR_URL"
      value: "https://dekoratoren.ekstern.dev.nav.no"

    - name: "SKATTETREKK_BACKEND_URL"
      value: "https://sokos-frivillig-skattetrekk-backend-q2.dev-fss-pub.nais.io"
    - name: "SKATTETREKK_BACKEND_SCOPE"
      value: "api://dev-fss.okonomi.sokos-frivillig-skattetrekk-backend-q2/.default"
    - name: "SKATTETREKK_BACKEND_AUDIENCE"
      value: "dev-fss:okonomi:sokos-frivillig-skattetrekk-backend-q2"

    - name: "REPRESENTASJON_BANNER_URL"
      value: "https://representasjon-banner-frontend-borger-q2.intern.dev.nav.no"
