name: Build/test and validate PR

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/dependabot-automerge.yaml"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"

jobs:
  build-pr:
    name: Build and test
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-pr.yaml@main
    secrets: inherit
    with:
      client-build-command: "pnpm run build:development"
      server-build-command: "pnpm run build"
