name: Build/test and validate PR

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"

jobs:
  build-pr:
    name: Build and test
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-pr-v2.yaml@main
    secrets: inherit
    with:
      build-command: "npm run build:development"
