name: Deploy application manual to dev

on:
  workflow_dispatch:
env:
  TZ: Europe/Oslo

permissions:
  contents: write
  id-token: write

jobs:
  build:
    name: Build/test & push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image-v2.yaml@main
    secrets: inherit
    with:
      build-command: "npm run build:development"
      image-tag: snapshot
      image-suffix: "development"
  deploy-dev:
    needs: build
    name: Deploy to dev-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-q2.yaml
      image: ${{ needs.build.outputs.image }}
