name: Deploy application manually

on:
  workflow_dispatch:
env:
  TZ: Europe/Oslo

permissions:
  contents: write
  id-token: write
  pull-requests: write
  deployments: write

jobs:
  build-push-image:
    permissions:
      contents: read
      id-token: write
    name: Build application & build/push image
    uses: navikt/mob-gha-workflows/.github/workflows/node-build-push-image.yaml@main
    secrets: inherit
    with:
      app-build-command: pnpm run build:development
      server-build-command: pnpm run build
      image-suffix: dev
      image-tag: snapshot

  deploy-dev:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      deployments: write
    needs: [build-push-image]
    name: Deploy to dev-gcp
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/naiserator-q2.yaml
      image: ${{ needs.build-push-image.outputs.image }}
